# Generated by Django 4.2.5 on 2023-10-01 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0002_remove_item_outside_rate_remove_item_product_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(db_column='item_id',
                 on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.item')),
                ('group_id', models.ForeignKey(db_column='group_id',
                 on_delete=django.db.models.deletion.CASCADE, related_name='+', to='group.group')),
                ('sale_rate', models.DecimalField(blank=True,
                 decimal_places=3, max_digits=7, null=True)),
                ('vehicle_rent', models.DecimalField(
                    blank=True, decimal_places=3, max_digits=7, null=True)),
                ('product_charge', models.DecimalField(
                    blank=True, decimal_places=3, max_digits=7, null=True)),
                ('wrapping', models.DecimalField(blank=True,
                 decimal_places=3, max_digits=7, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rates',
            },
        ),
    ]
