# Generated by Django 4.2.4 on 2023-10-10 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0013_alter_rates_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='reference_id',
            field=models.UUIDField(default=uuid.uuid4().hex),
        ),
    ]
