# Generated by Django 4.2.4 on 2023-10-05 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0010_alter_factory_reference_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_alter_account_reference_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(default='7a15973e69c140278c210690695cb572', max_length=32)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.factoryowner')),
                ('mode_of_payment', models.ForeignKey(db_column='mode_of_payment', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.account')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
