# Generated by Django 4.2.4 on 2023-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.UUIDField(default='32fbf0eebb614ee295ff79561748d61a'),
        ),
    ]
