# Generated by Django 4.2.5 on 2023-10-01 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('item', '0002_remove_item_outside_rate_remove_item_product_charge_and_more'),
        ('factory', '0002_remove_factoryowner_factory_id_factory_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.IntegerField()),
                ('total_amount', models.DecimalField(
                    decimal_places=3, max_digits=7)),
                ('amount_received', models.DecimalField(
                    decimal_places=3, max_digits=7)),
                ('total_vehicle_rent', models.DecimalField(
                    decimal_places=3, max_digits=7)),
                ('total_product_charge', models.DecimalField(
                    decimal_places=3, max_digits=7)),
                ('total_wrapping', models.DecimalField(
                    decimal_places=3, max_digits=7)),
                ('total', models.DecimalField(decimal_places=3, max_digits=7)),
                ('factory_id', models.ForeignKey(db_column='factory_id',
                 on_delete=django.db.models.deletion.CASCADE, related_name='+', to='factory.factory')),
                ('account_id', models.ForeignKey(db_column='account_id',
                 on_delete=django.db.models.deletion.CASCADE, related_name='+', to='account.account')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.ForeignKey(db_column='transaction_id',
                 on_delete=django.db.models.deletion.CASCADE, related_name='+', to='billing.transaction')),
                ('item_id', models.ForeignKey(db_column='item_id',
                 on_delete=django.db.models.deletion.CASCADE, related_name='+', to='item.item')),
                ('item_qty', models.DecimalField(decimal_places=3, max_digits=7)),
                ('item_rate', models.DecimalField(decimal_places=3, max_digits=7)),
                ('vehicle_rent', models.DecimalField(
                    decimal_places=3, max_digits=7)),
                ('product_charge', models.DecimalField(
                    decimal_places=3, max_digits=7)),
                ('wrapping', models.DecimalField(decimal_places=3, max_digits=7)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
