# Generated by Django 4.2.5 on 2023-10-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_transactiondetail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total',
        ),
    ]
