# Generated by Django 4.2.5 on 2023-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_transaction_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='item_unit',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default='a6a7584871a6410693fbff204186d718', max_length=32),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='reference_id',
            field=models.CharField(default='a6a7584871a6410693fbff204186d718', max_length=32),
        ),
    ]
