# Generated by Django 4.2.5 on 2023-10-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_group_reference_id'),
        ('billing', '0005_transactiondetail_item_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='group.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default='fdd34e9122a047fe9beff61e5c9812b3', max_length=32),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='reference_id',
            field=models.CharField(default='fdd34e9122a047fe9beff61e5c9812b3', max_length=32),
        ),
    ]
