# Generated by Django 4.2.4 on 2023-10-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_reference_id'),
        ('group', '0005_alter_group_reference_id'),
        ('item', '0008_alter_item_reference_id'),
        ('factory', '0006_alter_factory_reference_id_and_more'),
        ('billing', '0006_transactiondetail_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='account.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='factory_id',
            field=models.ForeignKey(db_column='factory_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.factory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default='80567d9a6a4c43fbb61e53116fcd562c', max_length=32),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='group.group'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='item.item'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='reference_id',
            field=models.CharField(default='80567d9a6a4c43fbb61e53116fcd562c', max_length=32),
        ),
    ]
