# Generated by Django 4.2.4 on 2023-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_remove_transactiondetail_item_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default='0d62dc69d14c4428a50e40b6a0190862', max_length=32),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='reference_id',
            field=models.CharField(default='0d62dc69d14c4428a50e40b6a0190862', max_length=32),
        ),
    ]
