# Generated by Django 4.2.4 on 2023-10-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_account_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reference_id',
            field=models.UUIDField(default='c41949d54081431382e93df0eaf3d938'),
        ),
    ]
