# Generated by Django 4.2.4 on 2023-10-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_group_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='reference_id',
            field=models.CharField(default='d0b2cf2fce5a413ab912026ae4bae467', max_length=32),
        ),
    ]
