# Generated by Django 4.2.5 on 2023-10-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='outside_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_charge',
        ),
        migrations.RemoveField(
            model_name='item',
            name='retail_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vehicle_rent_factory_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vehicle_rent_outside_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vehicle_rent_retail_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vehicle_rent_wholesale_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wholesale_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wrapping',
        ),
        migrations.AddField(
            model_name='item',
            name='opening_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
