# Generated by Django 4.2.5 on 2023-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_remove_item_outside_rate_remove_item_product_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
