# Generated by Django 4.2.4 on 2023-10-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reference_id',
            field=models.CharField(default='4f9cb0904dc44ccfa0f0b9c977a2e3bd', max_length=32),
        ),
    ]
