# Generated by Django 4.2.4 on 2023-10-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_item_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reference_id',
            field=models.CharField(default='0d62dc69d14c4428a50e40b6a0190862', max_length=32),
        ),
    ]
