# Generated by Django 4.2.5 on 2023-09-30 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=45)),
                ('factory_address', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factory',
            },
        ),
        migrations.CreateModel(
            name='FactoryOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('owner_name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('factory_id', models.OneToOneField(db_column='factory_id',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.factory')),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factoryOwner',
            },
        ),
    ]
