# Generated by Django 4.2.5 on 2023-10-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factoryowner',
            name='factory_id',
        ),
        migrations.AddField(
            model_name='factory',
            name='owner_id',
            field=models.OneToOneField(
                db_column='owner_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='factory.factoryowner'),
        ),
    ]
