# Generated by Django 4.2.4 on 2023-10-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_alter_factory_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factoryowner',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='reference_id',
            field=models.CharField(default='4f9cb0904dc44ccfa0f0b9c977a2e3bd', max_length=32),
        ),
        migrations.AlterField(
            model_name='factoryowner',
            name='reference_id',
            field=models.CharField(default='4f9cb0904dc44ccfa0f0b9c977a2e3bd', max_length=32),
        ),
    ]
