# Generated by Django 4.2.4 on 2023-10-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_alter_factory_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='reference_id',
            field=models.UUIDField(default='ce17f931fba3493182a7a8fe7593086e', unique=True),
        ),
        migrations.AlterField(
            model_name='factoryowner',
            name='reference_id',
            field=models.UUIDField(default='ce17f931fba3493182a7a8fe7593086e', unique=True),
        ),
    ]
