# Generated by Django 4.2.4 on 2023-10-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0014_alter_factory_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='reference_id',
            field=models.UUIDField(default='32fbf0eebb614ee295ff79561748d61a'),
        ),
        migrations.AlterField(
            model_name='factoryowner',
            name='reference_id',
            field=models.UUIDField(default='32fbf0eebb614ee295ff79561748d61a'),
        ),
    ]
