# Generated by Django 4.2.4 on 2023-10-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_alter_factory_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='reference_id',
            field=models.UUIDField(default='c41949d54081431382e93df0eaf3d938'),
        ),
        migrations.AlterField(
            model_name='factoryowner',
            name='reference_id',
            field=models.UUIDField(default='c41949d54081431382e93df0eaf3d938'),
        ),
    ]
